# Generated by Django 3.0.8 on 2020-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtrack',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
    ]
