# Generated by Django 3.0.8 on 2020-09-07 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_songtrack_duration_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='songtrack',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='songtrack',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='songtrack',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
