# Generated by Django 3.0.8 on 2020-09-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20200907_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtrack',
            name='external_urls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
